remote_theme: jackw01/jackw01.github.io
npm_url: https://www.npmjs.com/package/liora
title: Liora
hide_first_h1: true
nav_items:
  - 1:
    url: ./index
    text: Readme
  - 2:
    url: ./commanddoc
    text: Command Docs
